### ISSUE TITLE
overflow and scrollbars

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#8]
When the component is loaded, it pushes the scrolling back down. We should add an option that allow the component to have a overflow:scrolling. 

## Tasks

- [x] The user does not set any parameters (e.g. pdf_viewer(file)) -> we unwrap the PDF (no scroll bars, every page one after the other)
- [x] The user does set height = 700 (absolute number) -> then we show the scrollbars and limit the window to the height
- [x] ~~The user does set height = 80% (relative number) -> same as previous, show the scrollbars and limit the window to the height~~ because streamlet.setFrameHeight doesn't support relative number

**Comment by t29mato** [comment]
> The user does set height = 80% (relative number) -> same as previous, show the scrollbars and limit the window to the height

The argument of `Streamlit.setFrameHeight()` supports only numbers, not str like `80%`, so to support this feature, we need to calculate from the user's window size, which is not sure it can make it.

> The user does not set any parameters (e.g. pdf_viewer(file)) -> we unwrap the PDF (no scroll bars, every page one after the other)

I can make it. it would take 1 - 4 hours.

**Comment by lfoppiano** [comment]
> The argument of `Streamlit.setFrameHeight()` supports only numbers, not str like `80%`, so to support this feature, we need to calculate from the user's window size, which is not sure it can make it.

Let's drop it then, I can validate the parameter in the python part. 

> I can make it. it would take 1 - 4 hours. 

Isn't it already the current behaviour?

**Comment by t29mato** [comment]
> > I can make it. it would take 1 - 4 hours.
>
> Isn't it already the current behaviour?

Yeah, that's true. now, it's handling both cases

https://github.com/lfoppiano/streamlit-pdf-viewer/commit/9196b8509bf2f285062af0eff71799037d3d7be4

**Comment by lfoppiano** [comment]
@t29mato could you please summarise what exactly should be tested? The point number 2 is it implemented? 
Is this implemented in the `main` or as a PR?

**Comment by t29mato** [comment]
> summarise what exactly should be tested? 

1. **Test for Unset `height` (Default Behavior)**:
   - When `height` is not set (i.e., `None`), the PDF should display in its entirety without any overflow.

2. **Test for Set `height` (Numeric Value)**:
   - If a numeric value is assigned to `height`, the PDF should display with the specified height in pixels, and overflow should be enabled.

3. **Test for Invalid `height` Input**:
   - The function should throw an error if `height` is given a value other than a number or `None`.


> The point number 2 is it implemented?

Is point number 2 `The user does set height = 700 (absolute number) `? Then, yes, I've implemented it.


> Is this implemented in the `main` or as a PR?

Sorry, I don't understand this.
